// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { EmptyState } from '@heroui/react';
import type { TenoraEmptyStateProps } from './types';

function TenoraEmptyStateRoot(props: TenoraEmptyStateProps) {
  return <EmptyState {...props} />;
}



export const TenoraEmptyState = Object.assign(TenoraEmptyStateRoot, {
  Root: TenoraEmptyStateRoot,
});
