// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaModal } from './DunetaModal';
export type { DunetaModalProps, DunetaModalTriggerProps, DunetaModalBackdropProps, DunetaModalContainerProps, DunetaModalDialogProps, DunetaModalHeaderProps, DunetaModalIconProps, DunetaModalHeadingProps, DunetaModalBodyProps, DunetaModalFooterProps, DunetaModalCloseTriggerProps } from './types';
