// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaCard } from './DunetaCard';
export type { DunetaCardProps, DunetaCardHeaderProps, DunetaCardTitleProps, DunetaCardDescriptionProps, DunetaCardContentProps, DunetaCardFooterProps } from './types';
