// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraTabs } from './TenoraTabs';
export type { TenoraTabsProps, TenoraTabsListContainerProps, TenoraTabsListProps, TenoraTabsTabProps, TenoraTabsIndicatorProps, TenoraTabsSeparatorProps, TenoraTabsPanelProps } from './types';
