// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Tabs } from '@heroui/react';
import type { TenoraTabsProps, TenoraTabsListContainerProps, TenoraTabsListProps, TenoraTabsTabProps, TenoraTabsIndicatorProps, TenoraTabsSeparatorProps, TenoraTabsPanelProps } from './types';

function TenoraTabsRoot(props: TenoraTabsProps) {
  return <Tabs {...props} />;
}

function TenoraTabsListContainer(props: TenoraTabsListContainerProps) {
  return <Tabs.ListContainer {...props} />;
}

function TenoraTabsList(props: TenoraTabsListProps) {
  return <Tabs.List {...props} />;
}

function TenoraTabsTab(props: TenoraTabsTabProps) {
  return <Tabs.Tab {...props} />;
}

function TenoraTabsIndicator(props: TenoraTabsIndicatorProps) {
  return <Tabs.Indicator {...props} />;
}

function TenoraTabsSeparator(props: TenoraTabsSeparatorProps) {
  return <Tabs.Separator {...props} />;
}

function TenoraTabsPanel(props: TenoraTabsPanelProps) {
  return <Tabs.Panel {...props} />;
}

export const TenoraTabs = Object.assign(TenoraTabsRoot, {
  Root: TenoraTabsRoot,
  ListContainer: TenoraTabsListContainer,
  List: TenoraTabsList,
  Tab: TenoraTabsTab,
  Indicator: TenoraTabsIndicator,
  Separator: TenoraTabsSeparator,
  Panel: TenoraTabsPanel,
});
