// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Tabs } from '@heroui/react';

export type TenoraTabsProps = ComponentProps<typeof Tabs>;
export type TenoraTabsListContainerProps = ComponentProps<typeof Tabs.ListContainer>;
export type TenoraTabsListProps = ComponentProps<typeof Tabs.List>;
export type TenoraTabsTabProps = ComponentProps<typeof Tabs.Tab>;
export type TenoraTabsIndicatorProps = ComponentProps<typeof Tabs.Indicator>;
export type TenoraTabsSeparatorProps = ComponentProps<typeof Tabs.Separator>;
export type TenoraTabsPanelProps = ComponentProps<typeof Tabs.Panel>;
