// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Dropdown } from '@heroui/react';
import type { TenoraDropdownProps, TenoraDropdownTriggerProps, TenoraDropdownPopoverProps, TenoraDropdownMenuProps, TenoraDropdownSectionProps, TenoraDropdownItemProps, TenoraDropdownItemIndicatorProps, TenoraDropdownSubmenuIndicatorProps, TenoraDropdownSubmenuTriggerProps } from './types';

function TenoraDropdownRoot(props: TenoraDropdownProps) {
  return <Dropdown {...props} />;
}

function TenoraDropdownTrigger(props: TenoraDropdownTriggerProps) {
  return <Dropdown.Trigger {...props} />;
}

function TenoraDropdownPopover(props: TenoraDropdownPopoverProps) {
  return <Dropdown.Popover {...props} />;
}

function TenoraDropdownMenu(props: TenoraDropdownMenuProps) {
  return <Dropdown.Menu {...props} />;
}

function TenoraDropdownSection(props: TenoraDropdownSectionProps) {
  return <Dropdown.Section {...props} />;
}

function TenoraDropdownItem(props: TenoraDropdownItemProps) {
  return <Dropdown.Item {...props} />;
}

function TenoraDropdownItemIndicator(props: TenoraDropdownItemIndicatorProps) {
  return <Dropdown.ItemIndicator {...props} />;
}

function TenoraDropdownSubmenuIndicator(props: TenoraDropdownSubmenuIndicatorProps) {
  return <Dropdown.SubmenuIndicator {...props} />;
}

function TenoraDropdownSubmenuTrigger(props: TenoraDropdownSubmenuTriggerProps) {
  return <Dropdown.SubmenuTrigger {...props} />;
}

export const TenoraDropdown = Object.assign(TenoraDropdownRoot, {
  Root: TenoraDropdownRoot,
  Trigger: TenoraDropdownTrigger,
  Popover: TenoraDropdownPopover,
  Menu: TenoraDropdownMenu,
  Section: TenoraDropdownSection,
  Item: TenoraDropdownItem,
  ItemIndicator: TenoraDropdownItemIndicator,
  SubmenuIndicator: TenoraDropdownSubmenuIndicator,
  SubmenuTrigger: TenoraDropdownSubmenuTrigger,
});
