// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Dropdown } from '@heroui/react';

export type TenoraDropdownProps = ComponentProps<typeof Dropdown>;
export type TenoraDropdownTriggerProps = ComponentProps<typeof Dropdown.Trigger>;
export type TenoraDropdownPopoverProps = ComponentProps<typeof Dropdown.Popover>;
export type TenoraDropdownMenuProps = ComponentProps<typeof Dropdown.Menu>;
export type TenoraDropdownSectionProps = ComponentProps<typeof Dropdown.Section>;
export type TenoraDropdownItemProps = ComponentProps<typeof Dropdown.Item>;
export type TenoraDropdownItemIndicatorProps = ComponentProps<typeof Dropdown.ItemIndicator>;
export type TenoraDropdownSubmenuIndicatorProps = ComponentProps<typeof Dropdown.SubmenuIndicator>;
export type TenoraDropdownSubmenuTriggerProps = ComponentProps<typeof Dropdown.SubmenuTrigger>;
