// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraCard } from './TenoraCard';
export type { TenoraCardProps, TenoraCardHeaderProps, TenoraCardTitleProps, TenoraCardDescriptionProps, TenoraCardContentProps, TenoraCardFooterProps } from './types';
