// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Card } from '@heroui/react';
import type { TenoraCardProps, TenoraCardHeaderProps, TenoraCardTitleProps, TenoraCardDescriptionProps, TenoraCardContentProps, TenoraCardFooterProps } from './types';

function TenoraCardRoot(props: TenoraCardProps) {
  return <Card {...props} />;
}

function TenoraCardHeader(props: TenoraCardHeaderProps) {
  return <Card.Header {...props} />;
}

function TenoraCardTitle(props: TenoraCardTitleProps) {
  return <Card.Title {...props} />;
}

function TenoraCardDescription(props: TenoraCardDescriptionProps) {
  return <Card.Description {...props} />;
}

function TenoraCardContent(props: TenoraCardContentProps) {
  return <Card.Content {...props} />;
}

function TenoraCardFooter(props: TenoraCardFooterProps) {
  return <Card.Footer {...props} />;
}

export const TenoraCard = Object.assign(TenoraCardRoot, {
  Root: TenoraCardRoot,
  Header: TenoraCardHeader,
  Title: TenoraCardTitle,
  Description: TenoraCardDescription,
  Content: TenoraCardContent,
  Footer: TenoraCardFooter,
});
