// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Card } from '@heroui/react';

export type TenoraCardProps = ComponentProps<typeof Card>;
export type TenoraCardHeaderProps = ComponentProps<typeof Card.Header>;
export type TenoraCardTitleProps = ComponentProps<typeof Card.Title>;
export type TenoraCardDescriptionProps = ComponentProps<typeof Card.Description>;
export type TenoraCardContentProps = ComponentProps<typeof Card.Content>;
export type TenoraCardFooterProps = ComponentProps<typeof Card.Footer>;
