// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraFieldset } from './TenoraFieldset';
export type { TenoraFieldsetProps, TenoraFieldsetLegendProps, TenoraFieldsetGroupProps, TenoraFieldsetActionsProps } from './types';
