// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Fieldset } from '@heroui/react';
import type { TenoraFieldsetProps, TenoraFieldsetLegendProps, TenoraFieldsetGroupProps, TenoraFieldsetActionsProps } from './types';

function TenoraFieldsetRoot(props: TenoraFieldsetProps) {
  return <Fieldset {...props} />;
}

function TenoraFieldsetLegend(props: TenoraFieldsetLegendProps) {
  return <Fieldset.Legend {...props} />;
}

function TenoraFieldsetGroup(props: TenoraFieldsetGroupProps) {
  return <Fieldset.Group {...props} />;
}

function TenoraFieldsetActions(props: TenoraFieldsetActionsProps) {
  return <Fieldset.Actions {...props} />;
}

export const TenoraFieldset = Object.assign(TenoraFieldsetRoot, {
  Root: TenoraFieldsetRoot,
  Legend: TenoraFieldsetLegend,
  Group: TenoraFieldsetGroup,
  Actions: TenoraFieldsetActions,
});
