// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Fieldset } from '@heroui/react';

export type TenoraFieldsetProps = ComponentProps<typeof Fieldset>;
export type TenoraFieldsetLegendProps = ComponentProps<typeof Fieldset.Legend>;
export type TenoraFieldsetGroupProps = ComponentProps<typeof Fieldset.Group>;
export type TenoraFieldsetActionsProps = ComponentProps<typeof Fieldset.Actions>;
