// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ToggleButton } from '@heroui/react';
import type { TenoraToggleButtonProps } from './types';

function TenoraToggleButtonRoot(props: TenoraToggleButtonProps) {
  return <ToggleButton {...props} />;
}



export const TenoraToggleButton = Object.assign(TenoraToggleButtonRoot, {
  Root: TenoraToggleButtonRoot,
});
