// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ToggleButton } from '@heroui/react';

export type TenoraToggleButtonProps = ComponentProps<typeof ToggleButton>;
