// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Menu } from '@heroui/react';
import type { TenoraMenuProps, TenoraMenuItemProps } from './types';

function TenoraMenuRoot(props: TenoraMenuProps) {
  return <Menu {...props} />;
}

function TenoraMenuItem(props: TenoraMenuItemProps) {
  return <Menu.Item {...props} />;
}

export const TenoraMenu = Object.assign(TenoraMenuRoot, {
  Root: TenoraMenuRoot,
  Item: TenoraMenuItem,
});
