// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Menu } from '@heroui/react';

export type TenoraMenuProps = ComponentProps<typeof Menu>;
export type TenoraMenuItemProps = ComponentProps<typeof Menu.Item>;
