// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraTypography } from './TenoraTypography';
export type { TenoraTypographyProps, TenoraTypographyCodeProps, TenoraTypographyHeadingProps, TenoraTypographyParagraphProps, TenoraTypographyProseProps } from './types';
