// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Typography } from '@heroui/react';
import type { TenoraTypographyProps, TenoraTypographyCodeProps, TenoraTypographyHeadingProps, TenoraTypographyParagraphProps, TenoraTypographyProseProps } from './types';

function TenoraTypographyRoot(props: TenoraTypographyProps) {
  return <Typography {...props} />;
}

function TenoraTypographyCode(props: TenoraTypographyCodeProps) {
  return <Typography.Code {...props} />;
}

function TenoraTypographyHeading(props: TenoraTypographyHeadingProps) {
  return <Typography.Heading {...props} />;
}

function TenoraTypographyParagraph(props: TenoraTypographyParagraphProps) {
  return <Typography.Paragraph {...props} />;
}

function TenoraTypographyProse(props: TenoraTypographyProseProps) {
  return <Typography.Prose {...props} />;
}

export const TenoraTypography = Object.assign(TenoraTypographyRoot, {
  Root: TenoraTypographyRoot,
  Code: TenoraTypographyCode,
  Heading: TenoraTypographyHeading,
  Paragraph: TenoraTypographyParagraph,
  Prose: TenoraTypographyProse,
});
