// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Typography } from '@heroui/react';

export type TenoraTypographyProps = ComponentProps<typeof Typography>;
export type TenoraTypographyCodeProps = ComponentProps<typeof Typography.Code>;
export type TenoraTypographyHeadingProps = ComponentProps<typeof Typography.Heading>;
export type TenoraTypographyParagraphProps = ComponentProps<typeof Typography.Paragraph>;
export type TenoraTypographyProseProps = ComponentProps<typeof Typography.Prose>;
