// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { FieldError } from '@heroui/react';
import type { TenoraFieldErrorProps } from './types';

function TenoraFieldErrorRoot(props: TenoraFieldErrorProps) {
  return <FieldError {...props} />;
}



export const TenoraFieldError = Object.assign(TenoraFieldErrorRoot, {
  Root: TenoraFieldErrorRoot,
});
