// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Calendar } from '@heroui/react';
import type { DunetaCalendarProps } from './types';

export function DunetaCalendar(props: DunetaCalendarProps) {
  return <Calendar {...props} />;
}
