'use client';

import { IbaseButton as Button, IbaseCard as Card } from '../components';
import { appTheme } from '../themes';

const ArrowUpRight = () => <svg aria-hidden="true" viewBox="0 0 24 24" className="size-4" fill="none" stroke="currentColor" strokeWidth="2"><path d="M7 17 17 7M8 7h9v9" strokeLinecap="round" strokeLinejoin="round" /></svg>;
const Check = () => <svg aria-hidden="true" viewBox="0 0 24 24" className="size-4" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="m5 12 4.5 4.5L19 7" strokeLinecap="round" strokeLinejoin="round" /></svg>;

export function TenoraHome() {
  return (
    <main className={`${appTheme.page} min-h-screen overflow-hidden bg-[#07111f] px-5 pb-12 pt-5 text-slate-100 sm:px-8`}>
      <div className="ambient ambient-one" /><div className="ambient ambient-two" />
      <div className="relative mx-auto max-w-6xl">
        <header className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.035] px-4 py-3 backdrop-blur-xl sm:px-5">
          <a href="#top" className="flex items-center gap-3" aria-label="Tenora home"><span className="grid size-8 place-items-center rounded-xl bg-cyan-300 text-sm font-black text-slate-950">T</span><span className="text-sm font-semibold tracking-[0.18em] text-white">TENORA</span></a>
          <nav className="hidden items-center gap-6 text-sm text-slate-400 sm:flex" aria-label="Primary navigation"><a className="transition hover:text-white" href="#stack">Stack</a><a className="transition hover:text-white" href="#workflow">Workflow</a><a className="transition hover:text-white" href="#deploy">Deploy</a></nav>
          <a className="text-sm font-medium text-cyan-200 transition hover:text-white" href="https://github.com/BarryHoa/Tenora">GitHub <span aria-hidden="true">↗</span></a>
        </header>
        <section id="top" className="grid gap-12 pb-20 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-28">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-semibold tracking-wide text-cyan-100"><span className="size-1.5 rounded-full bg-cyan-300 shadow-[0_0_14px_3px_rgba(103,232,249,.5)]" />ONE TOOLKIT · ANY RUNTIME</div>
            <h1 className="max-w-3xl text-5xl font-semibold leading-[1.03] tracking-[-0.055em] text-white sm:text-6xl lg:text-7xl">Build once.<br /><span className="text-gradient">Ship anywhere.</span></h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">The TypeScript starter that keeps your Next.js product, Hono API, and shared core moving as one.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Button variant="primary" onPress={() => document.querySelector('#stack')?.scrollIntoView({ behavior: 'smooth' })}>Explore the stack <ArrowUpRight /></Button><Button variant="secondary" onPress={() => window.open('https://github.com/BarryHoa/Tenora', '_blank', 'noopener,noreferrer')}>View source</Button></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-400">{['Next.js 16', 'Hono API', 'Cloudflare ready'].map((item) => <span key={item} className="flex items-center gap-2"><Check />{item}</span>)}</div>
          </div>
          <Card className="hero-console border border-white/10 bg-slate-950/60 shadow-2xl shadow-cyan-950/30">
            <Card.Header className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex gap-1.5" aria-hidden="true"><span className="size-2.5 rounded-full bg-rose-400/80" /><span className="size-2.5 rounded-full bg-amber-300/80" /><span className="size-2.5 rounded-full bg-emerald-300/80" /></div><Card.Description className="font-mono text-[11px] uppercase tracking-[0.16em] text-slate-500">tenora / launch</Card.Description></Card.Header>
            <Card.Content className="space-y-5 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-400">Release status</p><p className="mt-1 text-2xl font-semibold tracking-tight text-white">Ready to ship</p></div><span className="rounded-full bg-emerald-300/10 px-3 py-1 text-xs font-semibold text-emerald-200">All systems go</span></div><div className="grid grid-cols-3 gap-3">{[['WEB', 'Next.js'], ['API', 'Hono'], ['CORE', 'TS']].map(([label, value]) => <div key={label} className="rounded-xl border border-white/8 bg-white/[0.035] p-3"><p className="text-[10px] font-semibold tracking-[0.14em] text-slate-500">{label}</p><p className="mt-2 text-sm font-medium text-slate-200">{value}</p></div>)}</div><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[0.045] p-4 font-mono text-sm leading-7 text-cyan-100"><span className="text-cyan-300">$</span> pnpm create tenora<br /><span className="text-emerald-300">✓</span> apps/web ready<br /><span className="text-emerald-300">✓</span> apps/api ready</div></Card.Content>
          </Card>
        </section>
        <section id="stack" className="scroll-mt-8 border-t border-white/10 py-16"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[0.18em] text-cyan-200">THE FOUNDATION</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">A stack with clear edges.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-400">Two focused applications. Shared packages where they belong. Nothing drifts.</p></div><div className="grid gap-4 md:grid-cols-3">{[['01', 'Web', 'Next.js app for fast, polished product experiences.', 'apps/web'], ['02', 'API', 'Hono routes that run on Node or Cloudflare Workers.', 'apps/api'], ['03', 'Core', 'Publishable server and client packages for shared logic.', '@tenora/*']].map(([number, title, description, path]) => <Card key={title} className="group border border-white/10 bg-white/[0.035] transition duration-300 hover:-translate-y-1 hover:border-cyan-200/35 hover:bg-white/[0.06]"><Card.Header className="px-6 pb-1 pt-6"><Card.Description className="text-xs font-semibold tracking-[0.18em] text-cyan-200">{number}</Card.Description><Card.Title className="mt-5 text-xl font-semibold text-white">{title}</Card.Title></Card.Header><Card.Content className="px-6 pb-6 pt-3"><Card.Description className="min-h-12 leading-6 text-slate-400">{description}</Card.Description><div className="mt-6 inline-flex rounded-lg border border-white/10 bg-slate-950/50 px-2.5 py-1 font-mono text-xs text-slate-300">{path}</div></Card.Content></Card>)}</div></section>
        <section id="workflow" className="grid gap-6 py-10 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><Card className="border border-white/10 bg-white/[0.035]"><Card.Content className="p-7"><p className="text-xs font-semibold tracking-[0.18em] text-cyan-200">ONE WORKFLOW</p><Card.Title className="mt-3 text-2xl font-semibold text-white">Local by default.</Card.Title><Card.Description className="mt-3 leading-7 text-slate-400">Start the web UI and API together, then choose the production runtime when you are ready.</Card.Description></Card.Content></Card><div className="hidden size-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-200 lg:grid">→</div><div id="deploy"><Card className="border border-cyan-300/20 bg-cyan-300/[0.07]"><Card.Content className="p-7"><p className="text-xs font-semibold tracking-[0.18em] text-cyan-100">EVERYWHERE READY</p><Card.Title className="mt-3 text-2xl font-semibold text-white">Deploy with intent.</Card.Title><Card.Description className="mt-3 leading-7 text-slate-300">Vercel for Next.js, Cloudflare for global Workers, or your own VPS when you want the controls.</Card.Description></Card.Content></Card></div></section>
      </div>
    </main>
  );
}
