// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ScrollShadow } from '@heroui/react';
import type { TenoraScrollShadowProps } from './types';

function TenoraScrollShadowRoot(props: TenoraScrollShadowProps) {
  return <ScrollShadow {...props} />;
}



export const TenoraScrollShadow = Object.assign(TenoraScrollShadowRoot, {
  Root: TenoraScrollShadowRoot,
});
