// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ScrollShadow } from '@heroui/react';

export type TenoraScrollShadowProps = ComponentProps<typeof ScrollShadow>;
