// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraBadge } from './TenoraBadge';
export type { TenoraBadgeProps, TenoraBadgeAnchorProps, TenoraBadgeLabelProps } from './types';
