// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Badge } from '@heroui/react';
import type { TenoraBadgeProps, TenoraBadgeAnchorProps, TenoraBadgeLabelProps } from './types';

function TenoraBadgeRoot(props: TenoraBadgeProps) {
  return <Badge {...props} />;
}

function TenoraBadgeAnchor(props: TenoraBadgeAnchorProps) {
  return <Badge.Anchor {...props} />;
}

function TenoraBadgeLabel(props: TenoraBadgeLabelProps) {
  return <Badge.Label {...props} />;
}

export const TenoraBadge = Object.assign(TenoraBadgeRoot, {
  Root: TenoraBadgeRoot,
  Anchor: TenoraBadgeAnchor,
  Label: TenoraBadgeLabel,
});
