// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Badge } from '@heroui/react';

export type TenoraBadgeProps = ComponentProps<typeof Badge>;
export type TenoraBadgeAnchorProps = ComponentProps<typeof Badge.Anchor>;
export type TenoraBadgeLabelProps = ComponentProps<typeof Badge.Label>;
