// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraBreadcrumbs } from './TenoraBreadcrumbs';
export type { TenoraBreadcrumbsProps, TenoraBreadcrumbsItemProps } from './types';
