// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Breadcrumbs } from '@heroui/react';
import type { TenoraBreadcrumbsProps, TenoraBreadcrumbsItemProps } from './types';

function TenoraBreadcrumbsRoot(props: TenoraBreadcrumbsProps) {
  return <Breadcrumbs {...props} />;
}

function TenoraBreadcrumbsItem(props: TenoraBreadcrumbsItemProps) {
  return <Breadcrumbs.Item {...props} />;
}

export const TenoraBreadcrumbs = Object.assign(TenoraBreadcrumbsRoot, {
  Root: TenoraBreadcrumbsRoot,
  Item: TenoraBreadcrumbsItem,
});
