// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Breadcrumbs } from '@heroui/react';

export type TenoraBreadcrumbsProps = ComponentProps<typeof Breadcrumbs>;
export type TenoraBreadcrumbsItemProps = ComponentProps<typeof Breadcrumbs.Item>;
