// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaAlert } from './DunetaAlert';
export type { DunetaAlertProps, DunetaAlertIndicatorProps, DunetaAlertContentProps, DunetaAlertTitleProps, DunetaAlertDescriptionProps } from './types';
