// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraAlert } from './TenoraAlert';
export type { TenoraAlertProps, TenoraAlertIndicatorProps, TenoraAlertContentProps, TenoraAlertTitleProps, TenoraAlertDescriptionProps } from './types';
