// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Alert } from '@heroui/react';
import type { TenoraAlertProps, TenoraAlertIndicatorProps, TenoraAlertContentProps, TenoraAlertTitleProps, TenoraAlertDescriptionProps } from './types';

function TenoraAlertRoot(props: TenoraAlertProps) {
  return <Alert {...props} />;
}

function TenoraAlertIndicator(props: TenoraAlertIndicatorProps) {
  return <Alert.Indicator {...props} />;
}

function TenoraAlertContent(props: TenoraAlertContentProps) {
  return <Alert.Content {...props} />;
}

function TenoraAlertTitle(props: TenoraAlertTitleProps) {
  return <Alert.Title {...props} />;
}

function TenoraAlertDescription(props: TenoraAlertDescriptionProps) {
  return <Alert.Description {...props} />;
}

export const TenoraAlert = Object.assign(TenoraAlertRoot, {
  Root: TenoraAlertRoot,
  Indicator: TenoraAlertIndicator,
  Content: TenoraAlertContent,
  Title: TenoraAlertTitle,
  Description: TenoraAlertDescription,
});
