// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Alert } from '@heroui/react';

export type TenoraAlertProps = ComponentProps<typeof Alert>;
export type TenoraAlertIndicatorProps = ComponentProps<typeof Alert.Indicator>;
export type TenoraAlertContentProps = ComponentProps<typeof Alert.Content>;
export type TenoraAlertTitleProps = ComponentProps<typeof Alert.Title>;
export type TenoraAlertDescriptionProps = ComponentProps<typeof Alert.Description>;
