// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraButtonGroup } from './TenoraButtonGroup';
export type { TenoraButtonGroupProps, TenoraButtonGroupSeparatorProps } from './types';
