// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ButtonGroup } from '@heroui/react';
import type { TenoraButtonGroupProps, TenoraButtonGroupSeparatorProps } from './types';

function TenoraButtonGroupRoot(props: TenoraButtonGroupProps) {
  return <ButtonGroup {...props} />;
}

function TenoraButtonGroupSeparator(props: TenoraButtonGroupSeparatorProps) {
  return <ButtonGroup.Separator {...props} />;
}

export const TenoraButtonGroup = Object.assign(TenoraButtonGroupRoot, {
  Root: TenoraButtonGroupRoot,
  Separator: TenoraButtonGroupSeparator,
});
