// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ButtonGroup } from '@heroui/react';

export type TenoraButtonGroupProps = ComponentProps<typeof ButtonGroup>;
export type TenoraButtonGroupSeparatorProps = ComponentProps<typeof ButtonGroup.Separator>;
