// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaDisclosure } from './DunetaDisclosure';
export type { DunetaDisclosureProps, DunetaDisclosureHeadingProps, DunetaDisclosureTriggerProps, DunetaDisclosureContentProps, DunetaDisclosureBodyProps, DunetaDisclosureIndicatorProps } from './types';
