// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorPicker } from '@heroui/react';
import type { TenoraColorPickerProps, TenoraColorPickerTriggerProps, TenoraColorPickerPopoverProps } from './types';

function TenoraColorPickerRoot(props: TenoraColorPickerProps) {
  return <ColorPicker {...props} />;
}

function TenoraColorPickerTrigger(props: TenoraColorPickerTriggerProps) {
  return <ColorPicker.Trigger {...props} />;
}

function TenoraColorPickerPopover(props: TenoraColorPickerPopoverProps) {
  return <ColorPicker.Popover {...props} />;
}

export const TenoraColorPicker = Object.assign(TenoraColorPickerRoot, {
  Root: TenoraColorPickerRoot,
  Trigger: TenoraColorPickerTrigger,
  Popover: TenoraColorPickerPopover,
});
