// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ColorPicker } from '@heroui/react';

export type TenoraColorPickerProps = ComponentProps<typeof ColorPicker>;
export type TenoraColorPickerTriggerProps = ComponentProps<typeof ColorPicker.Trigger>;
export type TenoraColorPickerPopoverProps = ComponentProps<typeof ColorPicker.Popover>;
