// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaSlider } from './DunetaSlider';
export type { DunetaSliderProps, DunetaSliderOutputProps, DunetaSliderTrackProps, DunetaSliderFillProps, DunetaSliderThumbProps, DunetaSliderMarksProps } from './types';
