// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaTabs } from './DunetaTabs';
export type { DunetaTabsProps, DunetaTabsListContainerProps, DunetaTabsListProps, DunetaTabsTabProps, DunetaTabsIndicatorProps, DunetaTabsSeparatorProps, DunetaTabsPanelProps } from './types';
