// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Spinner } from '@heroui/react';
import type { TenoraSpinnerProps } from './types';

function TenoraSpinnerRoot(props: TenoraSpinnerProps) {
  return <Spinner {...props} />;
}



export const TenoraSpinner = Object.assign(TenoraSpinnerRoot, {
  Root: TenoraSpinnerRoot,
});
