// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DateRangePicker } from '@heroui/react';
import type { TenoraDateRangePickerProps } from './types';

function TenoraDateRangePickerRoot(props: TenoraDateRangePickerProps) {
  return <DateRangePicker {...props} />;
}



export const TenoraDateRangePicker = Object.assign(TenoraDateRangePickerRoot, {
  Root: TenoraDateRangePickerRoot,
});
