// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaInputOTP } from './DunetaInputOTP';
export type { DunetaInputOTPProps, DunetaInputOTPGroupProps, DunetaInputOTPSlotProps, DunetaInputOTPSeparatorProps } from './types';
