// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Select } from '@heroui/react';
import type { TenoraSelectProps, TenoraSelectTriggerProps, TenoraSelectValueProps, TenoraSelectIndicatorProps, TenoraSelectPopoverProps } from './types';

function TenoraSelectRoot(props: TenoraSelectProps) {
  return <Select {...props} />;
}

function TenoraSelectTrigger(props: TenoraSelectTriggerProps) {
  return <Select.Trigger {...props} />;
}

function TenoraSelectValue(props: TenoraSelectValueProps) {
  return <Select.Value {...props} />;
}

function TenoraSelectIndicator(props: TenoraSelectIndicatorProps) {
  return <Select.Indicator {...props} />;
}

function TenoraSelectPopover(props: TenoraSelectPopoverProps) {
  return <Select.Popover {...props} />;
}

export const TenoraSelect = Object.assign(TenoraSelectRoot, {
  Root: TenoraSelectRoot,
  Trigger: TenoraSelectTrigger,
  Value: TenoraSelectValue,
  Indicator: TenoraSelectIndicator,
  Popover: TenoraSelectPopover,
});
