// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Link } from '@heroui/react';
import type { TenoraHrefLinkProps, TenoraHrefLinkIconProps } from './types';

function TenoraHrefLinkRoot(props: TenoraHrefLinkProps) {
  return <Link {...props} />;
}

function TenoraHrefLinkIcon(props: TenoraHrefLinkIconProps) {
  return <Link.Icon {...props} />;
}

export const TenoraHrefLink = Object.assign(TenoraHrefLinkRoot, {
  Root: TenoraHrefLinkRoot,
  Icon: TenoraHrefLinkIcon,
});
