// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Link } from '@heroui/react';

export type TenoraHrefLinkProps = ComponentProps<typeof Link>;
export type TenoraHrefLinkIconProps = ComponentProps<typeof Link.Icon>;
