// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DateField } from '@heroui/react';
import type { TenoraDateFieldProps, TenoraDateFieldGroupProps, TenoraDateFieldInputProps, TenoraDateFieldInputContainerProps, TenoraDateFieldSegmentProps, TenoraDateFieldPrefixProps, TenoraDateFieldSuffixProps } from './types';

function TenoraDateFieldRoot(props: TenoraDateFieldProps) {
  return <DateField {...props} />;
}

function TenoraDateFieldGroup(props: TenoraDateFieldGroupProps) {
  return <DateField.Group {...props} />;
}

function TenoraDateFieldInput(props: TenoraDateFieldInputProps) {
  return <DateField.Input {...props} />;
}

function TenoraDateFieldInputContainer(props: TenoraDateFieldInputContainerProps) {
  return <DateField.InputContainer {...props} />;
}

function TenoraDateFieldSegment(props: TenoraDateFieldSegmentProps) {
  return <DateField.Segment {...props} />;
}

function TenoraDateFieldPrefix(props: TenoraDateFieldPrefixProps) {
  return <DateField.Prefix {...props} />;
}

function TenoraDateFieldSuffix(props: TenoraDateFieldSuffixProps) {
  return <DateField.Suffix {...props} />;
}

export const TenoraDateField = Object.assign(TenoraDateFieldRoot, {
  Root: TenoraDateFieldRoot,
  Group: TenoraDateFieldGroup,
  Input: TenoraDateFieldInput,
  InputContainer: TenoraDateFieldInputContainer,
  Segment: TenoraDateFieldSegment,
  Prefix: TenoraDateFieldPrefix,
  Suffix: TenoraDateFieldSuffix,
});
