// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { DateField } from '@heroui/react';

export type TenoraDateFieldProps = ComponentProps<typeof DateField>;
export type TenoraDateFieldGroupProps = ComponentProps<typeof DateField.Group>;
export type TenoraDateFieldInputProps = ComponentProps<typeof DateField.Input>;
export type TenoraDateFieldInputContainerProps = ComponentProps<typeof DateField.InputContainer>;
export type TenoraDateFieldSegmentProps = ComponentProps<typeof DateField.Segment>;
export type TenoraDateFieldPrefixProps = ComponentProps<typeof DateField.Prefix>;
export type TenoraDateFieldSuffixProps = ComponentProps<typeof DateField.Suffix>;
