// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ProgressBar } from '@heroui/react';
import type { TenoraProgressBarProps } from './types';

function TenoraProgressBarRoot(props: TenoraProgressBarProps) {
  return <ProgressBar {...props} />;
}



export const TenoraProgressBar = Object.assign(TenoraProgressBarRoot, {
  Root: TenoraProgressBarRoot,
});
