// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ProgressBar } from '@heroui/react';

export type TenoraProgressBarProps = ComponentProps<typeof ProgressBar>;
