// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ProgressCircle } from '@heroui/react';
import type { TenoraProgressCircleProps } from './types';

function TenoraProgressCircleRoot(props: TenoraProgressCircleProps) {
  return <ProgressCircle {...props} />;
}



export const TenoraProgressCircle = Object.assign(TenoraProgressCircleRoot, {
  Root: TenoraProgressCircleRoot,
});
