// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraSlider } from './TenoraSlider';
export type { TenoraSliderProps, TenoraSliderOutputProps, TenoraSliderTrackProps, TenoraSliderFillProps, TenoraSliderThumbProps, TenoraSliderMarksProps } from './types';
