// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Slider } from '@heroui/react';
import type { TenoraSliderProps, TenoraSliderOutputProps, TenoraSliderTrackProps, TenoraSliderFillProps, TenoraSliderThumbProps, TenoraSliderMarksProps } from './types';

function TenoraSliderRoot(props: TenoraSliderProps) {
  return <Slider {...props} />;
}

function TenoraSliderOutput(props: TenoraSliderOutputProps) {
  return <Slider.Output {...props} />;
}

function TenoraSliderTrack(props: TenoraSliderTrackProps) {
  return <Slider.Track {...props} />;
}

function TenoraSliderFill(props: TenoraSliderFillProps) {
  return <Slider.Fill {...props} />;
}

function TenoraSliderThumb(props: TenoraSliderThumbProps) {
  return <Slider.Thumb {...props} />;
}

function TenoraSliderMarks(props: TenoraSliderMarksProps) {
  return <Slider.Marks {...props} />;
}

export const TenoraSlider = Object.assign(TenoraSliderRoot, {
  Root: TenoraSliderRoot,
  Output: TenoraSliderOutput,
  Track: TenoraSliderTrack,
  Fill: TenoraSliderFill,
  Thumb: TenoraSliderThumb,
  Marks: TenoraSliderMarks,
});
