// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Slider } from '@heroui/react';

export type TenoraSliderProps = ComponentProps<typeof Slider>;
export type TenoraSliderOutputProps = ComponentProps<typeof Slider.Output>;
export type TenoraSliderTrackProps = ComponentProps<typeof Slider.Track>;
export type TenoraSliderFillProps = ComponentProps<typeof Slider.Fill>;
export type TenoraSliderThumbProps = ComponentProps<typeof Slider.Thumb>;
export type TenoraSliderMarksProps = ComponentProps<typeof Slider.Marks>;
