// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaFieldset } from './DunetaFieldset';
export type { DunetaFieldsetProps, DunetaFieldsetLegendProps, DunetaFieldsetGroupProps, DunetaFieldsetActionsProps } from './types';
