// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraKbd } from './TenoraKbd';
export type { TenoraKbdProps, TenoraKbdAbbrProps, TenoraKbdContentProps } from './types';
