// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Kbd } from '@heroui/react';
import type { TenoraKbdProps, TenoraKbdAbbrProps, TenoraKbdContentProps } from './types';

function TenoraKbdRoot(props: TenoraKbdProps) {
  return <Kbd {...props} />;
}

function TenoraKbdAbbr(props: TenoraKbdAbbrProps) {
  return <Kbd.Abbr {...props} />;
}

function TenoraKbdContent(props: TenoraKbdContentProps) {
  return <Kbd.Content {...props} />;
}

export const TenoraKbd = Object.assign(TenoraKbdRoot, {
  Root: TenoraKbdRoot,
  Abbr: TenoraKbdAbbr,
  Content: TenoraKbdContent,
});
