// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Kbd } from '@heroui/react';

export type TenoraKbdProps = ComponentProps<typeof Kbd>;
export type TenoraKbdAbbrProps = ComponentProps<typeof Kbd.Abbr>;
export type TenoraKbdContentProps = ComponentProps<typeof Kbd.Content>;
