// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraColorArea } from './TenoraColorArea';
export type { TenoraColorAreaProps, TenoraColorAreaThumbProps } from './types';
