// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorArea } from '@heroui/react';
import type { TenoraColorAreaProps, TenoraColorAreaThumbProps } from './types';

function TenoraColorAreaRoot(props: TenoraColorAreaProps) {
  return <ColorArea {...props} />;
}

function TenoraColorAreaThumb(props: TenoraColorAreaThumbProps) {
  return <ColorArea.Thumb {...props} />;
}

export const TenoraColorArea = Object.assign(TenoraColorAreaRoot, {
  Root: TenoraColorAreaRoot,
  Thumb: TenoraColorAreaThumb,
});
