// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ColorArea } from '@heroui/react';

export type TenoraColorAreaProps = ComponentProps<typeof ColorArea>;
export type TenoraColorAreaThumbProps = ComponentProps<typeof ColorArea.Thumb>;
