// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Checkbox } from '@heroui/react';
import type { TenoraCheckboxProps } from './types';

function TenoraCheckboxRoot(props: TenoraCheckboxProps) {
  return <Checkbox {...props} />;
}



export const TenoraCheckbox = Object.assign(TenoraCheckboxRoot, {
  Root: TenoraCheckboxRoot,
});
