// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Surface } from '@heroui/react';
import type { TenoraSurfaceProps } from './types';

function TenoraSurfaceRoot(props: TenoraSurfaceProps) {
  return <Surface {...props} />;
}



export const TenoraSurface = Object.assign(TenoraSurfaceRoot, {
  Root: TenoraSurfaceRoot,
});
