// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaAutocomplete } from './DunetaAutocomplete';
export type { DunetaAutocompleteProps, DunetaAutocompleteTriggerProps, DunetaAutocompleteValueProps, DunetaAutocompleteIndicatorProps, DunetaAutocompletePopoverProps, DunetaAutocompleteFilterProps, DunetaAutocompleteClearButtonProps } from './types';
