// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Drawer } from '@heroui/react';
import type { TenoraDrawerProps } from './types';

function TenoraDrawerRoot(props: TenoraDrawerProps) {
  return <Drawer {...props} />;
}



export const TenoraDrawer = Object.assign(TenoraDrawerRoot, {
  Root: TenoraDrawerRoot,
});
