// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Input } from '@heroui/react';
import type { TenoraInputProps } from './types';

function TenoraInputRoot(props: TenoraInputProps) {
  return <Input {...props} />;
}



export const TenoraInput = Object.assign(TenoraInputRoot, {
  Root: TenoraInputRoot,
});
