// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Input } from '@heroui/react';

export type TenoraInputProps = ComponentProps<typeof Input>;

export type { TenoraDatePickerProps } from './TenoraDatePicker';
export type { TenoraInputEmailProps } from './TenoraInputEmail';
export type { TenoraInputNumberProps, TenoraInputNumberValue } from './TenoraInputNumber';
export type { TenoraInputPasswordProps } from './TenoraInputPassword';
export type { TenoraInputPhoneProps } from './TenoraInputPhone';
export type { TenoraInputSearchProps } from './TenoraInputSearch';
export type { TenoraTextAreaProps } from './TenoraTextArea';
