// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaAccordion } from './DunetaAccordion';
export type { DunetaAccordionProps, DunetaAccordionItemProps, DunetaAccordionHeadingProps, DunetaAccordionTriggerProps, DunetaAccordionPanelProps, DunetaAccordionIndicatorProps, DunetaAccordionBodyProps } from './types';
