// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ListBox } from '@heroui/react';
import type { TenoraListBoxProps, TenoraListBoxItemProps } from './types';

function TenoraListBoxRoot(props: TenoraListBoxProps) {
  return <ListBox {...props} />;
}

function TenoraListBoxItem(props: TenoraListBoxItemProps) {
  return <ListBox.Item {...props} />;
}

export const TenoraListBox = Object.assign(TenoraListBoxRoot, {
  Root: TenoraListBoxRoot,
  Item: TenoraListBoxItem,
});
