// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ListBox } from '@heroui/react';

export type TenoraListBoxProps = ComponentProps<typeof ListBox>;
export type TenoraListBoxItemProps = ComponentProps<typeof ListBox.Item>;
