// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraDisclosure } from './TenoraDisclosure';
export type { TenoraDisclosureProps, TenoraDisclosureHeadingProps, TenoraDisclosureTriggerProps, TenoraDisclosureContentProps, TenoraDisclosureBodyProps, TenoraDisclosureIndicatorProps } from './types';
