// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Disclosure } from '@heroui/react';
import type { TenoraDisclosureProps, TenoraDisclosureHeadingProps, TenoraDisclosureTriggerProps, TenoraDisclosureContentProps, TenoraDisclosureBodyProps, TenoraDisclosureIndicatorProps } from './types';

function TenoraDisclosureRoot(props: TenoraDisclosureProps) {
  return <Disclosure {...props} />;
}

function TenoraDisclosureHeading(props: TenoraDisclosureHeadingProps) {
  return <Disclosure.Heading {...props} />;
}

function TenoraDisclosureTrigger(props: TenoraDisclosureTriggerProps) {
  return <Disclosure.Trigger {...props} />;
}

function TenoraDisclosureContent(props: TenoraDisclosureContentProps) {
  return <Disclosure.Content {...props} />;
}

function TenoraDisclosureBody(props: TenoraDisclosureBodyProps) {
  return <Disclosure.Body {...props} />;
}

function TenoraDisclosureIndicator(props: TenoraDisclosureIndicatorProps) {
  return <Disclosure.Indicator {...props} />;
}

export const TenoraDisclosure = Object.assign(TenoraDisclosureRoot, {
  Root: TenoraDisclosureRoot,
  Heading: TenoraDisclosureHeading,
  Trigger: TenoraDisclosureTrigger,
  Content: TenoraDisclosureContent,
  Body: TenoraDisclosureBody,
  Indicator: TenoraDisclosureIndicator,
});
