// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Disclosure } from '@heroui/react';

export type TenoraDisclosureProps = ComponentProps<typeof Disclosure>;
export type TenoraDisclosureHeadingProps = ComponentProps<typeof Disclosure.Heading>;
export type TenoraDisclosureTriggerProps = ComponentProps<typeof Disclosure.Trigger>;
export type TenoraDisclosureContentProps = ComponentProps<typeof Disclosure.Content>;
export type TenoraDisclosureBodyProps = ComponentProps<typeof Disclosure.Body>;
export type TenoraDisclosureIndicatorProps = ComponentProps<typeof Disclosure.Indicator>;
