// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { CloseButton } from '@heroui/react';
import type { TenoraCloseButtonProps } from './types';

function TenoraCloseButtonRoot(props: TenoraCloseButtonProps) {
  return <CloseButton {...props} />;
}



export const TenoraCloseButton = Object.assign(TenoraCloseButtonRoot, {
  Root: TenoraCloseButtonRoot,
});
