// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraTimeField } from './TenoraTimeField';
export type { TenoraTimeFieldProps, TenoraTimeFieldGroupProps, TenoraTimeFieldInputProps, TenoraTimeFieldInputContainerProps, TenoraTimeFieldSegmentProps, TenoraTimeFieldPrefixProps, TenoraTimeFieldSuffixProps } from './types';
