// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TimeField } from '@heroui/react';
import type { TenoraTimeFieldProps, TenoraTimeFieldGroupProps, TenoraTimeFieldInputProps, TenoraTimeFieldInputContainerProps, TenoraTimeFieldSegmentProps, TenoraTimeFieldPrefixProps, TenoraTimeFieldSuffixProps } from './types';

function TenoraTimeFieldRoot(props: TenoraTimeFieldProps) {
  return <TimeField {...props} />;
}

function TenoraTimeFieldGroup(props: TenoraTimeFieldGroupProps) {
  return <TimeField.Group {...props} />;
}

function TenoraTimeFieldInput(props: TenoraTimeFieldInputProps) {
  return <TimeField.Input {...props} />;
}

function TenoraTimeFieldInputContainer(props: TenoraTimeFieldInputContainerProps) {
  return <TimeField.InputContainer {...props} />;
}

function TenoraTimeFieldSegment(props: TenoraTimeFieldSegmentProps) {
  return <TimeField.Segment {...props} />;
}

function TenoraTimeFieldPrefix(props: TenoraTimeFieldPrefixProps) {
  return <TimeField.Prefix {...props} />;
}

function TenoraTimeFieldSuffix(props: TenoraTimeFieldSuffixProps) {
  return <TimeField.Suffix {...props} />;
}

export const TenoraTimeField = Object.assign(TenoraTimeFieldRoot, {
  Root: TenoraTimeFieldRoot,
  Group: TenoraTimeFieldGroup,
  Input: TenoraTimeFieldInput,
  InputContainer: TenoraTimeFieldInputContainer,
  Segment: TenoraTimeFieldSegment,
  Prefix: TenoraTimeFieldPrefix,
  Suffix: TenoraTimeFieldSuffix,
});
