// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { TimeField } from '@heroui/react';

export type TenoraTimeFieldProps = ComponentProps<typeof TimeField>;
export type TenoraTimeFieldGroupProps = ComponentProps<typeof TimeField.Group>;
export type TenoraTimeFieldInputProps = ComponentProps<typeof TimeField.Input>;
export type TenoraTimeFieldInputContainerProps = ComponentProps<typeof TimeField.InputContainer>;
export type TenoraTimeFieldSegmentProps = ComponentProps<typeof TimeField.Segment>;
export type TenoraTimeFieldPrefixProps = ComponentProps<typeof TimeField.Prefix>;
export type TenoraTimeFieldSuffixProps = ComponentProps<typeof TimeField.Suffix>;
