// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaColorSlider } from './DunetaColorSlider';
export type { DunetaColorSliderProps, DunetaColorSliderOutputProps, DunetaColorSliderTrackProps, DunetaColorSliderThumbProps } from './types';
