// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraTable } from './TenoraTable';
export type { TenoraTableProps, TenoraTableBodyProps, TenoraTableCellProps, TenoraTableCollectionProps, TenoraTableColumnProps, TenoraTableColumnResizerProps, TenoraTableContentProps, TenoraTableFooterProps, TenoraTableHeaderProps, TenoraTableRowProps, TenoraTableScrollContainerProps, TenoraTableResizableContainerProps } from './types';
