// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Table } from '@heroui/react';
import type {
  TenoraTableProps,
  TenoraTableBodyProps,
  TenoraTableCellProps,
  TenoraTableCollectionProps,
  TenoraTableColumnProps,
  TenoraTableColumnResizerProps,
  TenoraTableContentProps,
  TenoraTableFooterProps,
  TenoraTableHeaderProps,
  TenoraTableRowProps,
  TenoraTableScrollContainerProps,
  TenoraTableResizableContainerProps,
} from './types';

function TenoraTableRoot(props: TenoraTableProps) {
  return <Table {...props} />;
}

function TenoraTableBody(props: TenoraTableBodyProps) {
  return <Table.Body {...props} />;
}

function TenoraTableCell(props: TenoraTableCellProps) {
  return <Table.Cell {...props} />;
}

function TenoraTableCollection(props: TenoraTableCollectionProps) {
  return <Table.Collection {...props} />;
}

function TenoraTableColumn(props: TenoraTableColumnProps) {
  return <Table.Column {...props} />;
}

function TenoraTableColumnResizer(props: TenoraTableColumnResizerProps) {
  return <Table.ColumnResizer {...props} />;
}

function TenoraTableContent(props: TenoraTableContentProps) {
  return <Table.Content {...props} />;
}

function TenoraTableFooter(props: TenoraTableFooterProps) {
  return <Table.Footer {...props} />;
}

function TenoraTableHeader(props: TenoraTableHeaderProps) {
  return <Table.Header {...props} />;
}

function TenoraTableRow(props: TenoraTableRowProps) {
  return <Table.Row {...props} />;
}

function TenoraTableScrollContainer(props: TenoraTableScrollContainerProps) {
  return <Table.ScrollContainer {...props} />;
}

function TenoraTableResizableContainer(props: TenoraTableResizableContainerProps) {
  return <Table.ResizableContainer {...props} />;
}

export const TenoraTable = Object.assign(TenoraTableRoot, {
  Root: TenoraTableRoot,
  Body: TenoraTableBody,
  Cell: TenoraTableCell,
  Collection: TenoraTableCollection,
  Column: TenoraTableColumn,
  ColumnResizer: TenoraTableColumnResizer,
  Content: TenoraTableContent,
  Footer: TenoraTableFooter,
  Header: TenoraTableHeader,
  Row: TenoraTableRow,
  ScrollContainer: TenoraTableScrollContainer,
  ResizableContainer: TenoraTableResizableContainer,
});
