// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Table } from '@heroui/react';

export type TenoraTableProps = ComponentProps<typeof Table>;
export type TenoraTableBodyProps = ComponentProps<typeof Table.Body>;
export type TenoraTableCellProps = ComponentProps<typeof Table.Cell>;
export type TenoraTableCollectionProps = ComponentProps<typeof Table.Collection>;
export type TenoraTableColumnProps = ComponentProps<typeof Table.Column>;
export type TenoraTableColumnResizerProps = ComponentProps<typeof Table.ColumnResizer>;
export type TenoraTableContentProps = ComponentProps<typeof Table.Content>;
export type TenoraTableFooterProps = ComponentProps<typeof Table.Footer>;
export type TenoraTableHeaderProps = ComponentProps<typeof Table.Header>;
export type TenoraTableRowProps = ComponentProps<typeof Table.Row>;
export type TenoraTableScrollContainerProps = ComponentProps<typeof Table.ScrollContainer>;
export type TenoraTableResizableContainerProps = ComponentProps<typeof Table.ResizableContainer>;
