// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Button } from '@heroui/react';
import type { TenoraButtonProps } from './types';

function TenoraButtonRoot(props: TenoraButtonProps) {
  return <Button {...props} />;
}



export const TenoraButton = Object.assign(TenoraButtonRoot, {
  Root: TenoraButtonRoot,
});
