// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Button } from '@heroui/react';

export type TenoraButtonProps = ComponentProps<typeof Button>;
