// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraColorField } from './TenoraColorField';
export type { TenoraColorFieldProps, TenoraColorFieldGroupProps, TenoraColorFieldInputProps, TenoraColorFieldPrefixProps, TenoraColorFieldSuffixProps } from './types';
