// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorField } from '@heroui/react';
import type { TenoraColorFieldProps, TenoraColorFieldGroupProps, TenoraColorFieldInputProps, TenoraColorFieldPrefixProps, TenoraColorFieldSuffixProps } from './types';

function TenoraColorFieldRoot(props: TenoraColorFieldProps) {
  return <ColorField {...props} />;
}

function TenoraColorFieldGroup(props: TenoraColorFieldGroupProps) {
  return <ColorField.Group {...props} />;
}

function TenoraColorFieldInput(props: TenoraColorFieldInputProps) {
  return <ColorField.Input {...props} />;
}

function TenoraColorFieldPrefix(props: TenoraColorFieldPrefixProps) {
  return <ColorField.Prefix {...props} />;
}

function TenoraColorFieldSuffix(props: TenoraColorFieldSuffixProps) {
  return <ColorField.Suffix {...props} />;
}

export const TenoraColorField = Object.assign(TenoraColorFieldRoot, {
  Root: TenoraColorFieldRoot,
  Group: TenoraColorFieldGroup,
  Input: TenoraColorFieldInput,
  Prefix: TenoraColorFieldPrefix,
  Suffix: TenoraColorFieldSuffix,
});
