// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ColorField } from '@heroui/react';

export type TenoraColorFieldProps = ComponentProps<typeof ColorField>;
export type TenoraColorFieldGroupProps = ComponentProps<typeof ColorField.Group>;
export type TenoraColorFieldInputProps = ComponentProps<typeof ColorField.Input>;
export type TenoraColorFieldPrefixProps = ComponentProps<typeof ColorField.Prefix>;
export type TenoraColorFieldSuffixProps = ComponentProps<typeof ColorField.Suffix>;
