// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Pagination } from '@heroui/react';
import type { TenoraPaginationProps, TenoraPaginationContentProps } from './types';

function TenoraPaginationRoot(props: TenoraPaginationProps) {
  return <Pagination {...props} />;
}

function TenoraPaginationContent(props: TenoraPaginationContentProps) {
  return <Pagination.Content {...props} />;
}

export const TenoraPagination = Object.assign(TenoraPaginationRoot, {
  Root: TenoraPaginationRoot,
  Content: TenoraPaginationContent,
});
