// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Pagination } from '@heroui/react';
import { cn } from '../../helpers';
import type {
  TenoraPaginationContentProps,
  TenoraPaginationEllipsisProps,
  TenoraPaginationItemProps,
  TenoraPaginationLinkProps,
  TenoraPaginationNextIconProps,
  TenoraPaginationNextProps,
  TenoraPaginationPreviousIconProps,
  TenoraPaginationPreviousProps,
  TenoraPaginationProps,
  TenoraPaginationSummaryProps,
} from './types';

function TenoraPaginationRoot(props: TenoraPaginationProps) {
  return <Pagination {...props} />;
}

function TenoraPaginationSummary(props: TenoraPaginationSummaryProps) {
  return <Pagination.Summary {...props} />;
}

function TenoraPaginationContent(props: TenoraPaginationContentProps) {
  return <Pagination.Content {...props} />;
}

function TenoraPaginationItem(props: TenoraPaginationItemProps) {
  return <Pagination.Item {...props} />;
}

const ACTIVE_LINK_CLASS =
  'data-[active=true]:[--pagination-link-bg:var(--accent)] data-[active=true]:[--pagination-link-fg:var(--accent-foreground)] data-[active=true]:[--pagination-link-bg-hover:var(--accent-hover)] data-[active=true]:[--pagination-link-bg-pressed:var(--accent-hover)]';

function TenoraPaginationLink({
  className,
  isActive,
  ...props
}: TenoraPaginationLinkProps) {
  return (
    <Pagination.Link
      className={cn(isActive && ACTIVE_LINK_CLASS, className)}
      isActive={isActive}
      {...props}
    />
  );
}

function TenoraPaginationPrevious(props: TenoraPaginationPreviousProps) {
  return <Pagination.Previous {...props} />;
}

function TenoraPaginationPreviousIcon(props: TenoraPaginationPreviousIconProps) {
  return <Pagination.PreviousIcon {...props} />;
}

function TenoraPaginationNext(props: TenoraPaginationNextProps) {
  return <Pagination.Next {...props} />;
}

function TenoraPaginationNextIcon(props: TenoraPaginationNextIconProps) {
  return <Pagination.NextIcon {...props} />;
}

function TenoraPaginationEllipsis(props: TenoraPaginationEllipsisProps) {
  return <Pagination.Ellipsis {...props} />;
}

export const TenoraPagination = Object.assign(TenoraPaginationRoot, {
  Root: TenoraPaginationRoot,
  Summary: TenoraPaginationSummary,
  Content: TenoraPaginationContent,
  Item: TenoraPaginationItem,
  Link: TenoraPaginationLink,
  Previous: TenoraPaginationPrevious,
  PreviousIcon: TenoraPaginationPreviousIcon,
  Next: TenoraPaginationNext,
  NextIcon: TenoraPaginationNextIcon,
  Ellipsis: TenoraPaginationEllipsis,
});
