// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Pagination } from '@heroui/react';

export type TenoraPaginationProps = ComponentProps<typeof Pagination>;
export type TenoraPaginationContentProps = ComponentProps<typeof Pagination.Content>;
