// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraColorSwatchPicker } from './TenoraColorSwatchPicker';
export type { TenoraColorSwatchPickerProps, TenoraColorSwatchPickerItemProps, TenoraColorSwatchPickerSwatchProps, TenoraColorSwatchPickerIndicatorProps } from './types';
