// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSwatchPicker } from '@heroui/react';
import type { TenoraColorSwatchPickerProps, TenoraColorSwatchPickerItemProps, TenoraColorSwatchPickerSwatchProps, TenoraColorSwatchPickerIndicatorProps } from './types';

function TenoraColorSwatchPickerRoot(props: TenoraColorSwatchPickerProps) {
  return <ColorSwatchPicker {...props} />;
}

function TenoraColorSwatchPickerItem(props: TenoraColorSwatchPickerItemProps) {
  return <ColorSwatchPicker.Item {...props} />;
}

function TenoraColorSwatchPickerSwatch(props: TenoraColorSwatchPickerSwatchProps) {
  return <ColorSwatchPicker.Swatch {...props} />;
}

function TenoraColorSwatchPickerIndicator(props: TenoraColorSwatchPickerIndicatorProps) {
  return <ColorSwatchPicker.Indicator {...props} />;
}

export const TenoraColorSwatchPicker = Object.assign(TenoraColorSwatchPickerRoot, {
  Root: TenoraColorSwatchPickerRoot,
  Item: TenoraColorSwatchPickerItem,
  Swatch: TenoraColorSwatchPickerSwatch,
  Indicator: TenoraColorSwatchPickerIndicator,
});
