// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ColorSwatchPicker } from '@heroui/react';

export type TenoraColorSwatchPickerProps = ComponentProps<typeof ColorSwatchPicker>;
export type TenoraColorSwatchPickerItemProps = ComponentProps<typeof ColorSwatchPicker.Item>;
export type TenoraColorSwatchPickerSwatchProps = ComponentProps<typeof ColorSwatchPicker.Swatch>;
export type TenoraColorSwatchPickerIndicatorProps = ComponentProps<typeof ColorSwatchPicker.Indicator>;
