// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaTable } from './DunetaTable';
export type { DunetaTableProps, DunetaTableBodyProps, DunetaTableCellProps, DunetaTableCollectionProps, DunetaTableColumnProps, DunetaTableColumnResizerProps, DunetaTableContentProps, DunetaTableFooterProps, DunetaTableHeaderProps, DunetaTableRowProps, DunetaTableScrollContainerProps, DunetaTableResizableContainerProps } from './types';
