// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraColorSlider } from './TenoraColorSlider';
export type { TenoraColorSliderProps, TenoraColorSliderOutputProps, TenoraColorSliderTrackProps, TenoraColorSliderThumbProps } from './types';
