// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSlider } from '@heroui/react';
import type { TenoraColorSliderProps, TenoraColorSliderOutputProps, TenoraColorSliderTrackProps, TenoraColorSliderThumbProps } from './types';

function TenoraColorSliderRoot(props: TenoraColorSliderProps) {
  return <ColorSlider {...props} />;
}

function TenoraColorSliderOutput(props: TenoraColorSliderOutputProps) {
  return <ColorSlider.Output {...props} />;
}

function TenoraColorSliderTrack(props: TenoraColorSliderTrackProps) {
  return <ColorSlider.Track {...props} />;
}

function TenoraColorSliderThumb(props: TenoraColorSliderThumbProps) {
  return <ColorSlider.Thumb {...props} />;
}

export const TenoraColorSlider = Object.assign(TenoraColorSliderRoot, {
  Root: TenoraColorSliderRoot,
  Output: TenoraColorSliderOutput,
  Track: TenoraColorSliderTrack,
  Thumb: TenoraColorSliderThumb,
});
