// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ColorSlider } from '@heroui/react';

export type TenoraColorSliderProps = ComponentProps<typeof ColorSlider>;
export type TenoraColorSliderOutputProps = ComponentProps<typeof ColorSlider.Output>;
export type TenoraColorSliderTrackProps = ComponentProps<typeof ColorSlider.Track>;
export type TenoraColorSliderThumbProps = ComponentProps<typeof ColorSlider.Thumb>;
