// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraModal } from './TenoraModal';
export type { TenoraModalProps, TenoraModalTriggerProps, TenoraModalBackdropProps, TenoraModalContainerProps, TenoraModalDialogProps, TenoraModalHeaderProps, TenoraModalIconProps, TenoraModalHeadingProps, TenoraModalBodyProps, TenoraModalFooterProps, TenoraModalCloseTriggerProps } from './types';
