// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Modal } from '@heroui/react';
import type { TenoraModalProps, TenoraModalTriggerProps, TenoraModalBackdropProps, TenoraModalContainerProps, TenoraModalDialogProps, TenoraModalHeaderProps, TenoraModalIconProps, TenoraModalHeadingProps, TenoraModalBodyProps, TenoraModalFooterProps, TenoraModalCloseTriggerProps } from './types';

function TenoraModalRoot(props: TenoraModalProps) {
  return <Modal {...props} />;
}

function TenoraModalTrigger(props: TenoraModalTriggerProps) {
  return <Modal.Trigger {...props} />;
}

function TenoraModalBackdrop(props: TenoraModalBackdropProps) {
  return <Modal.Backdrop {...props} />;
}

function TenoraModalContainer(props: TenoraModalContainerProps) {
  return <Modal.Container {...props} />;
}

function TenoraModalDialog(props: TenoraModalDialogProps) {
  return <Modal.Dialog {...props} />;
}

function TenoraModalHeader(props: TenoraModalHeaderProps) {
  return <Modal.Header {...props} />;
}

function TenoraModalIcon(props: TenoraModalIconProps) {
  return <Modal.Icon {...props} />;
}

function TenoraModalHeading(props: TenoraModalHeadingProps) {
  return <Modal.Heading {...props} />;
}

function TenoraModalBody(props: TenoraModalBodyProps) {
  return <Modal.Body {...props} />;
}

function TenoraModalFooter(props: TenoraModalFooterProps) {
  return <Modal.Footer {...props} />;
}

function TenoraModalCloseTrigger(props: TenoraModalCloseTriggerProps) {
  return <Modal.CloseTrigger {...props} />;
}

export const TenoraModal = Object.assign(TenoraModalRoot, {
  Root: TenoraModalRoot,
  Trigger: TenoraModalTrigger,
  Backdrop: TenoraModalBackdrop,
  Container: TenoraModalContainer,
  Dialog: TenoraModalDialog,
  Header: TenoraModalHeader,
  Icon: TenoraModalIcon,
  Heading: TenoraModalHeading,
  Body: TenoraModalBody,
  Footer: TenoraModalFooter,
  CloseTrigger: TenoraModalCloseTrigger,
});
