// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Modal } from '@heroui/react';

export type TenoraModalProps = ComponentProps<typeof Modal>;
export type TenoraModalTriggerProps = ComponentProps<typeof Modal.Trigger>;
export type TenoraModalBackdropProps = ComponentProps<typeof Modal.Backdrop>;
export type TenoraModalContainerProps = ComponentProps<typeof Modal.Container>;
export type TenoraModalDialogProps = ComponentProps<typeof Modal.Dialog>;
export type TenoraModalHeaderProps = ComponentProps<typeof Modal.Header>;
export type TenoraModalIconProps = ComponentProps<typeof Modal.Icon>;
export type TenoraModalHeadingProps = ComponentProps<typeof Modal.Heading>;
export type TenoraModalBodyProps = ComponentProps<typeof Modal.Body>;
export type TenoraModalFooterProps = ComponentProps<typeof Modal.Footer>;
export type TenoraModalCloseTriggerProps = ComponentProps<typeof Modal.CloseTrigger>;
