// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { RadioGroup } from '@heroui/react';
import type { TenoraRadioGroupProps } from './types';

function TenoraRadioGroupRoot(props: TenoraRadioGroupProps) {
  return <RadioGroup {...props} />;
}



export const TenoraRadioGroup = Object.assign(TenoraRadioGroupRoot, {
  Root: TenoraRadioGroupRoot,
});
