// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { RadioGroup } from '@heroui/react';

export type TenoraRadioGroupProps = ComponentProps<typeof RadioGroup>;
