// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraAutocomplete } from './TenoraAutocomplete';
export type { TenoraAutocompleteProps, TenoraAutocompleteTriggerProps, TenoraAutocompleteValueProps, TenoraAutocompleteIndicatorProps, TenoraAutocompletePopoverProps, TenoraAutocompleteFilterProps, TenoraAutocompleteClearButtonProps } from './types';
