// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Autocomplete } from '@heroui/react';
import type { TenoraAutocompleteProps, TenoraAutocompleteTriggerProps, TenoraAutocompleteValueProps, TenoraAutocompleteIndicatorProps, TenoraAutocompletePopoverProps, TenoraAutocompleteFilterProps, TenoraAutocompleteClearButtonProps } from './types';

function TenoraAutocompleteRoot(props: TenoraAutocompleteProps) {
  return <Autocomplete {...props} />;
}

function TenoraAutocompleteTrigger(props: TenoraAutocompleteTriggerProps) {
  return <Autocomplete.Trigger {...props} />;
}

function TenoraAutocompleteValue(props: TenoraAutocompleteValueProps) {
  return <Autocomplete.Value {...props} />;
}

function TenoraAutocompleteIndicator(props: TenoraAutocompleteIndicatorProps) {
  return <Autocomplete.Indicator {...props} />;
}

function TenoraAutocompletePopover(props: TenoraAutocompletePopoverProps) {
  return <Autocomplete.Popover {...props} />;
}

function TenoraAutocompleteFilter(props: TenoraAutocompleteFilterProps) {
  return <Autocomplete.Filter {...props} />;
}

function TenoraAutocompleteClearButton(props: TenoraAutocompleteClearButtonProps) {
  return <Autocomplete.ClearButton {...props} />;
}

export const TenoraAutocomplete = Object.assign(TenoraAutocompleteRoot, {
  Root: TenoraAutocompleteRoot,
  Trigger: TenoraAutocompleteTrigger,
  Value: TenoraAutocompleteValue,
  Indicator: TenoraAutocompleteIndicator,
  Popover: TenoraAutocompletePopover,
  Filter: TenoraAutocompleteFilter,
  ClearButton: TenoraAutocompleteClearButton,
});
