// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Autocomplete } from '@heroui/react';

export type TenoraAutocompleteProps = ComponentProps<typeof Autocomplete>;
export type TenoraAutocompleteTriggerProps = ComponentProps<typeof Autocomplete.Trigger>;
export type TenoraAutocompleteValueProps = ComponentProps<typeof Autocomplete.Value>;
export type TenoraAutocompleteIndicatorProps = ComponentProps<typeof Autocomplete.Indicator>;
export type TenoraAutocompletePopoverProps = ComponentProps<typeof Autocomplete.Popover>;
export type TenoraAutocompleteFilterProps = ComponentProps<typeof Autocomplete.Filter>;
export type TenoraAutocompleteClearButtonProps = ComponentProps<typeof Autocomplete.ClearButton>;
