// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Meter } from '@heroui/react';
import type { TenoraMeterProps } from './types';

function TenoraMeterRoot(props: TenoraMeterProps) {
  return <Meter {...props} />;
}



export const TenoraMeter = Object.assign(TenoraMeterRoot, {
  Root: TenoraMeterRoot,
});
