// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ErrorMessage } from '@heroui/react';
import type { TenoraErrorMessageProps } from './types';

function TenoraErrorMessageRoot(props: TenoraErrorMessageProps) {
  return <ErrorMessage {...props} />;
}



export const TenoraErrorMessage = Object.assign(TenoraErrorMessageRoot, {
  Root: TenoraErrorMessageRoot,
});
