// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaRangeCalendar } from './DunetaRangeCalendar';
export type { DunetaRangeCalendarProps, DunetaRangeCalendarHeaderProps } from './types';
