// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { SwitchGroup } from '@heroui/react';
import type { TenoraSwitchGroupProps } from './types';

function TenoraSwitchGroupRoot(props: TenoraSwitchGroupProps) {
  return <SwitchGroup {...props} />;
}



export const TenoraSwitchGroup = Object.assign(TenoraSwitchGroupRoot, {
  Root: TenoraSwitchGroupRoot,
});
