// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Chip } from '@heroui/react';
import type { TenoraChipProps, TenoraChipLabelProps } from './types';

function TenoraChipRoot(props: TenoraChipProps) {
  return <Chip {...props} />;
}

function TenoraChipLabel(props: TenoraChipLabelProps) {
  return <Chip.Label {...props} />;
}

export const TenoraChip = Object.assign(TenoraChipRoot, {
  Root: TenoraChipRoot,
  Label: TenoraChipLabel,
});
