// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Chip } from '@heroui/react';

export type TenoraChipProps = ComponentProps<typeof Chip>;
export type TenoraChipLabelProps = ComponentProps<typeof Chip.Label>;
