// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraToggleButtonGroup } from './TenoraToggleButtonGroup';
export type { TenoraToggleButtonGroupProps, TenoraToggleButtonGroupSeparatorProps } from './types';
