// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ToggleButtonGroup } from '@heroui/react';
import type { TenoraToggleButtonGroupProps, TenoraToggleButtonGroupSeparatorProps } from './types';

function TenoraToggleButtonGroupRoot(props: TenoraToggleButtonGroupProps) {
  return <ToggleButtonGroup {...props} />;
}

function TenoraToggleButtonGroupSeparator(props: TenoraToggleButtonGroupSeparatorProps) {
  return <ToggleButtonGroup.Separator {...props} />;
}

export const TenoraToggleButtonGroup = Object.assign(TenoraToggleButtonGroupRoot, {
  Root: TenoraToggleButtonGroupRoot,
  Separator: TenoraToggleButtonGroupSeparator,
});
