// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ToggleButtonGroup } from '@heroui/react';

export type TenoraToggleButtonGroupProps = ComponentProps<typeof ToggleButtonGroup>;
export type TenoraToggleButtonGroupSeparatorProps = ComponentProps<typeof ToggleButtonGroup.Separator>;
