// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraAvatar } from './TenoraAvatar';
export type { TenoraAvatarProps, TenoraAvatarImageProps, TenoraAvatarFallbackProps } from './types';
