// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Avatar } from '@heroui/react';
import type { TenoraAvatarProps, TenoraAvatarImageProps, TenoraAvatarFallbackProps } from './types';

function TenoraAvatarRoot(props: TenoraAvatarProps) {
  return <Avatar {...props} />;
}

function TenoraAvatarImage(props: TenoraAvatarImageProps) {
  return <Avatar.Image {...props} />;
}

function TenoraAvatarFallback(props: TenoraAvatarFallbackProps) {
  return <Avatar.Fallback {...props} />;
}

export const TenoraAvatar = Object.assign(TenoraAvatarRoot, {
  Root: TenoraAvatarRoot,
  Image: TenoraAvatarImage,
  Fallback: TenoraAvatarFallback,
});
