// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Avatar } from '@heroui/react';

export type TenoraAvatarProps = ComponentProps<typeof Avatar>;
export type TenoraAvatarImageProps = ComponentProps<typeof Avatar.Image>;
export type TenoraAvatarFallbackProps = ComponentProps<typeof Avatar.Fallback>;
