// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TagGroup } from '@heroui/react';
import type { TenoraTagGroupProps, TenoraTagGroupListProps } from './types';

function TenoraTagGroupRoot(props: TenoraTagGroupProps) {
  return <TagGroup {...props} />;
}

function TenoraTagGroupList(props: TenoraTagGroupListProps) {
  return <TagGroup.List {...props} />;
}

export const TenoraTagGroup = Object.assign(TenoraTagGroupRoot, {
  Root: TenoraTagGroupRoot,
  List: TenoraTagGroupList,
});
