// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { TagGroup } from '@heroui/react';

export type TenoraTagGroupProps = ComponentProps<typeof TagGroup>;
export type TenoraTagGroupListProps = ComponentProps<typeof TagGroup.List>;
