// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaInputGroup } from './DunetaInputGroup';
export type { DunetaInputGroupProps, DunetaInputGroupInputProps, DunetaInputGroupTextAreaProps, DunetaInputGroupPrefixProps, DunetaInputGroupSuffixProps } from './types';
