// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraInputGroup } from './TenoraInputGroup';
export type { TenoraInputGroupProps, TenoraInputGroupInputProps, TenoraInputGroupTextAreaProps, TenoraInputGroupPrefixProps, TenoraInputGroupSuffixProps } from './types';
