// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { InputGroup } from '@heroui/react';
import type { TenoraInputGroupProps, TenoraInputGroupInputProps, TenoraInputGroupTextAreaProps, TenoraInputGroupPrefixProps, TenoraInputGroupSuffixProps } from './types';

function TenoraInputGroupRoot(props: TenoraInputGroupProps) {
  return <InputGroup {...props} />;
}

function TenoraInputGroupInput(props: TenoraInputGroupInputProps) {
  return <InputGroup.Input {...props} />;
}

function TenoraInputGroupTextArea(props: TenoraInputGroupTextAreaProps) {
  return <InputGroup.TextArea {...props} />;
}

function TenoraInputGroupPrefix(props: TenoraInputGroupPrefixProps) {
  return <InputGroup.Prefix {...props} />;
}

function TenoraInputGroupSuffix(props: TenoraInputGroupSuffixProps) {
  return <InputGroup.Suffix {...props} />;
}

export const TenoraInputGroup = Object.assign(TenoraInputGroupRoot, {
  Root: TenoraInputGroupRoot,
  Input: TenoraInputGroupInput,
  TextArea: TenoraInputGroupTextArea,
  Prefix: TenoraInputGroupPrefix,
  Suffix: TenoraInputGroupSuffix,
});
