// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { InputGroup } from '@heroui/react';

export type TenoraInputGroupProps = ComponentProps<typeof InputGroup>;
export type TenoraInputGroupInputProps = ComponentProps<typeof InputGroup.Input>;
export type TenoraInputGroupTextAreaProps = ComponentProps<typeof InputGroup.TextArea>;
export type TenoraInputGroupPrefixProps = ComponentProps<typeof InputGroup.Prefix>;
export type TenoraInputGroupSuffixProps = ComponentProps<typeof InputGroup.Suffix>;
