// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraInputOTP } from './TenoraInputOTP';
export type { TenoraInputOTPProps, TenoraInputOTPGroupProps, TenoraInputOTPSlotProps, TenoraInputOTPSeparatorProps } from './types';
