// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { InputOTP } from '@heroui/react';
import type { TenoraInputOTPProps, TenoraInputOTPGroupProps, TenoraInputOTPSlotProps, TenoraInputOTPSeparatorProps } from './types';

function TenoraInputOTPRoot(props: TenoraInputOTPProps) {
  return <InputOTP {...props} />;
}

function TenoraInputOTPGroup(props: TenoraInputOTPGroupProps) {
  return <InputOTP.Group {...props} />;
}

function TenoraInputOTPSlot(props: TenoraInputOTPSlotProps) {
  return <InputOTP.Slot {...props} />;
}

function TenoraInputOTPSeparator(props: TenoraInputOTPSeparatorProps) {
  return <InputOTP.Separator {...props} />;
}

export const TenoraInputOTP = Object.assign(TenoraInputOTPRoot, {
  Root: TenoraInputOTPRoot,
  Group: TenoraInputOTPGroup,
  Slot: TenoraInputOTPSlot,
  Separator: TenoraInputOTPSeparator,
});
