// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { InputOTP } from '@heroui/react';

export type TenoraInputOTPProps = ComponentProps<typeof InputOTP>;
export type TenoraInputOTPGroupProps = ComponentProps<typeof InputOTP.Group>;
export type TenoraInputOTPSlotProps = ComponentProps<typeof InputOTP.Slot>;
export type TenoraInputOTPSeparatorProps = ComponentProps<typeof InputOTP.Separator>;
