// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Toolbar } from '@heroui/react';
import type { TenoraToolbarProps } from './types';

function TenoraToolbarRoot(props: TenoraToolbarProps) {
  return <Toolbar {...props} />;
}



export const TenoraToolbar = Object.assign(TenoraToolbarRoot, {
  Root: TenoraToolbarRoot,
});
