// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaColorArea } from './DunetaColorArea';
export type { DunetaColorAreaProps, DunetaColorAreaThumbProps } from './types';
