// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraNumberField } from './TenoraNumberField';
export type { TenoraNumberFieldProps, TenoraNumberFieldGroupProps, TenoraNumberFieldInputProps, TenoraNumberFieldIncrementButtonProps, TenoraNumberFieldDecrementButtonProps } from './types';
