// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { NumberField } from '@heroui/react';
import type { TenoraNumberFieldProps, TenoraNumberFieldGroupProps, TenoraNumberFieldInputProps, TenoraNumberFieldIncrementButtonProps, TenoraNumberFieldDecrementButtonProps } from './types';

function TenoraNumberFieldRoot(props: TenoraNumberFieldProps) {
  return <NumberField {...props} />;
}

function TenoraNumberFieldGroup(props: TenoraNumberFieldGroupProps) {
  return <NumberField.Group {...props} />;
}

function TenoraNumberFieldInput(props: TenoraNumberFieldInputProps) {
  return <NumberField.Input {...props} />;
}

function TenoraNumberFieldIncrementButton(props: TenoraNumberFieldIncrementButtonProps) {
  return <NumberField.IncrementButton {...props} />;
}

function TenoraNumberFieldDecrementButton(props: TenoraNumberFieldDecrementButtonProps) {
  return <NumberField.DecrementButton {...props} />;
}

export const TenoraNumberField = Object.assign(TenoraNumberFieldRoot, {
  Root: TenoraNumberFieldRoot,
  Group: TenoraNumberFieldGroup,
  Input: TenoraNumberFieldInput,
  IncrementButton: TenoraNumberFieldIncrementButton,
  DecrementButton: TenoraNumberFieldDecrementButton,
});
