// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { NumberField } from '@heroui/react';

export type TenoraNumberFieldProps = ComponentProps<typeof NumberField>;
export type TenoraNumberFieldGroupProps = ComponentProps<typeof NumberField.Group>;
export type TenoraNumberFieldInputProps = ComponentProps<typeof NumberField.Input>;
export type TenoraNumberFieldIncrementButtonProps = ComponentProps<typeof NumberField.IncrementButton>;
export type TenoraNumberFieldDecrementButtonProps = ComponentProps<typeof NumberField.DecrementButton>;
