// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Description } from '@heroui/react';
import type { TenoraDescriptionProps } from './types';

function TenoraDescriptionRoot(props: TenoraDescriptionProps) {
  return <Description {...props} />;
}



export const TenoraDescription = Object.assign(TenoraDescriptionRoot, {
  Root: TenoraDescriptionRoot,
});
