// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Description } from '@heroui/react';

export type TenoraDescriptionProps = ComponentProps<typeof Description>;
