// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { RangeCalendar } from '@heroui/react';
import type { TenoraRangeCalendarProps, TenoraRangeCalendarHeaderProps } from './types';

function TenoraRangeCalendarRoot(props: TenoraRangeCalendarProps) {
  return <RangeCalendar {...props} />;
}

function TenoraRangeCalendarHeader(props: TenoraRangeCalendarHeaderProps) {
  return <RangeCalendar.Header {...props} />;
}

export const TenoraRangeCalendar = Object.assign(TenoraRangeCalendarRoot, {
  Root: TenoraRangeCalendarRoot,
  Header: TenoraRangeCalendarHeader,
});
