// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { RangeCalendar } from '@heroui/react';

export type TenoraRangeCalendarProps = ComponentProps<typeof RangeCalendar>;
export type TenoraRangeCalendarHeaderProps = ComponentProps<typeof RangeCalendar.Header>;
