// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraAccordion } from './TenoraAccordion';
export type { TenoraAccordionProps, TenoraAccordionItemProps, TenoraAccordionHeadingProps, TenoraAccordionTriggerProps, TenoraAccordionPanelProps, TenoraAccordionIndicatorProps, TenoraAccordionBodyProps } from './types';
