// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Accordion } from '@heroui/react';
import type { TenoraAccordionProps, TenoraAccordionItemProps, TenoraAccordionHeadingProps, TenoraAccordionTriggerProps, TenoraAccordionPanelProps, TenoraAccordionIndicatorProps, TenoraAccordionBodyProps } from './types';

function TenoraAccordionRoot(props: TenoraAccordionProps) {
  return <Accordion {...props} />;
}

function TenoraAccordionItem(props: TenoraAccordionItemProps) {
  return <Accordion.Item {...props} />;
}

function TenoraAccordionHeading(props: TenoraAccordionHeadingProps) {
  return <Accordion.Heading {...props} />;
}

function TenoraAccordionTrigger(props: TenoraAccordionTriggerProps) {
  return <Accordion.Trigger {...props} />;
}

function TenoraAccordionPanel(props: TenoraAccordionPanelProps) {
  return <Accordion.Panel {...props} />;
}

function TenoraAccordionIndicator(props: TenoraAccordionIndicatorProps) {
  return <Accordion.Indicator {...props} />;
}

function TenoraAccordionBody(props: TenoraAccordionBodyProps) {
  return <Accordion.Body {...props} />;
}

export const TenoraAccordion = Object.assign(TenoraAccordionRoot, {
  Root: TenoraAccordionRoot,
  Item: TenoraAccordionItem,
  Heading: TenoraAccordionHeading,
  Trigger: TenoraAccordionTrigger,
  Panel: TenoraAccordionPanel,
  Indicator: TenoraAccordionIndicator,
  Body: TenoraAccordionBody,
});
