// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Accordion } from '@heroui/react';

export type TenoraAccordionProps = ComponentProps<typeof Accordion>;
export type TenoraAccordionItemProps = ComponentProps<typeof Accordion.Item>;
export type TenoraAccordionHeadingProps = ComponentProps<typeof Accordion.Heading>;
export type TenoraAccordionTriggerProps = ComponentProps<typeof Accordion.Trigger>;
export type TenoraAccordionPanelProps = ComponentProps<typeof Accordion.Panel>;
export type TenoraAccordionIndicatorProps = ComponentProps<typeof Accordion.Indicator>;
export type TenoraAccordionBodyProps = ComponentProps<typeof Accordion.Body>;
