// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraComboBox } from './TenoraComboBox';
export type { TenoraComboBoxProps, TenoraComboBoxInputGroupProps, TenoraComboBoxTriggerProps, TenoraComboBoxPopoverProps } from './types';
