// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ComboBox } from '@heroui/react';
import type { TenoraComboBoxProps, TenoraComboBoxInputGroupProps, TenoraComboBoxTriggerProps, TenoraComboBoxPopoverProps } from './types';

function TenoraComboBoxRoot(props: TenoraComboBoxProps) {
  return <ComboBox {...props} />;
}

function TenoraComboBoxInputGroup(props: TenoraComboBoxInputGroupProps) {
  return <ComboBox.InputGroup {...props} />;
}

function TenoraComboBoxTrigger(props: TenoraComboBoxTriggerProps) {
  return <ComboBox.Trigger {...props} />;
}

function TenoraComboBoxPopover(props: TenoraComboBoxPopoverProps) {
  return <ComboBox.Popover {...props} />;
}

export const TenoraComboBox = Object.assign(TenoraComboBoxRoot, {
  Root: TenoraComboBoxRoot,
  InputGroup: TenoraComboBoxInputGroup,
  Trigger: TenoraComboBoxTrigger,
  Popover: TenoraComboBoxPopover,
});
