// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { ComboBox } from '@heroui/react';

export type TenoraComboBoxProps = ComponentProps<typeof ComboBox>;
export type TenoraComboBoxInputGroupProps = ComponentProps<typeof ComboBox.InputGroup>;
export type TenoraComboBoxTriggerProps = ComponentProps<typeof ComboBox.Trigger>;
export type TenoraComboBoxPopoverProps = ComponentProps<typeof ComboBox.Popover>;
