// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaTypography } from './DunetaTypography';
export type { DunetaTypographyProps, DunetaTypographyCodeProps, DunetaTypographyHeadingProps, DunetaTypographyParagraphProps, DunetaTypographyProseProps } from './types';
