// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Separator } from '@heroui/react';
import type { TenoraSeparatorProps } from './types';

function TenoraSeparatorRoot(props: TenoraSeparatorProps) {
  return <Separator {...props} />;
}



export const TenoraSeparator = Object.assign(TenoraSeparatorRoot, {
  Root: TenoraSeparatorRoot,
});
