// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Separator } from '@heroui/react';

export type TenoraSeparatorProps = ComponentProps<typeof Separator>;
