// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { DisclosureGroup } from '@heroui/react';
import type { TenoraDisclosureGroupProps } from './types';

function TenoraDisclosureGroupRoot(props: TenoraDisclosureGroupProps) {
  return <DisclosureGroup {...props} />;
}



export const TenoraDisclosureGroup = Object.assign(TenoraDisclosureGroupRoot, {
  Root: TenoraDisclosureGroupRoot,
});
