// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Switch } from '@heroui/react';
import type { TenoraSwitchProps } from './types';

function TenoraSwitchRoot(props: TenoraSwitchProps) {
  return <Switch {...props} />;
}



export const TenoraSwitch = Object.assign(TenoraSwitchRoot, {
  Root: TenoraSwitchRoot,
});
