// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Form } from '@heroui/react';
import type { TenoraFormProps } from './types';

function TenoraFormRoot(props: TenoraFormProps) {
  return <Form {...props} />;
}



export const TenoraForm = Object.assign(TenoraFormRoot, {
  Root: TenoraFormRoot,
});
