// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Form } from '@heroui/react';

export type TenoraFormProps = ComponentProps<typeof Form>;

export type { TenoraFormFieldProps } from './TenoraFormField';
export type { TenoraFormRadioFieldProps, TenoraFormRadioOption } from './TenoraFormRadioField';
export type { TenoraFormSectionProps } from './TenoraFormSection';
