// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaKbd } from './DunetaKbd';
export type { DunetaKbdProps, DunetaKbdAbbrProps, DunetaKbdContentProps } from './types';
