// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaTooltip } from './DunetaTooltip';
export type { DunetaTooltipProps, DunetaTooltipTriggerProps, DunetaTooltipContentProps, DunetaTooltipArrowProps } from './types';
