// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Label } from '@heroui/react';
import type { TenoraLabelProps } from './types';

function TenoraLabelRoot(props: TenoraLabelProps) {
  return <Label {...props} />;
}



export const TenoraLabel = Object.assign(TenoraLabelRoot, {
  Root: TenoraLabelRoot,
});
