// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { SearchField } from '@heroui/react';
import type { TenoraSearchFieldProps, TenoraSearchFieldGroupProps, TenoraSearchFieldInputProps, TenoraSearchFieldSearchIconProps, TenoraSearchFieldClearButtonProps } from './types';

function TenoraSearchFieldRoot(props: TenoraSearchFieldProps) {
  return <SearchField {...props} />;
}

function TenoraSearchFieldGroup(props: TenoraSearchFieldGroupProps) {
  return <SearchField.Group {...props} />;
}

function TenoraSearchFieldInput(props: TenoraSearchFieldInputProps) {
  return <SearchField.Input {...props} />;
}

function TenoraSearchFieldSearchIcon(props: TenoraSearchFieldSearchIconProps) {
  return <SearchField.SearchIcon {...props} />;
}

function TenoraSearchFieldClearButton(props: TenoraSearchFieldClearButtonProps) {
  return <SearchField.ClearButton {...props} />;
}

export const TenoraSearchField = Object.assign(TenoraSearchFieldRoot, {
  Root: TenoraSearchFieldRoot,
  Group: TenoraSearchFieldGroup,
  Input: TenoraSearchFieldInput,
  SearchIcon: TenoraSearchFieldSearchIcon,
  ClearButton: TenoraSearchFieldClearButton,
});
