// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { SearchField } from '@heroui/react';

export type TenoraSearchFieldProps = ComponentProps<typeof SearchField>;
export type TenoraSearchFieldGroupProps = ComponentProps<typeof SearchField.Group>;
export type TenoraSearchFieldInputProps = ComponentProps<typeof SearchField.Input>;
export type TenoraSearchFieldSearchIconProps = ComponentProps<typeof SearchField.SearchIcon>;
export type TenoraSearchFieldClearButtonProps = ComponentProps<typeof SearchField.ClearButton>;
