// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Skeleton } from '@heroui/react';
import type { TenoraSkeletonProps } from './types';

function TenoraSkeletonRoot(props: TenoraSkeletonProps) {
  return <Skeleton {...props} />;
}



export const TenoraSkeleton = Object.assign(TenoraSkeletonRoot, {
  Root: TenoraSkeletonRoot,
});
