// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Skeleton } from '@heroui/react';

export type TenoraSkeletonProps = ComponentProps<typeof Skeleton>;
