// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { TextField } from '@heroui/react';
import type { TenoraTextFieldProps } from './types';

function TenoraTextFieldRoot(props: TenoraTextFieldProps) {
  return <TextField {...props} />;
}



export const TenoraTextField = Object.assign(TenoraTextFieldRoot, {
  Root: TenoraTextFieldRoot,
});
