// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraTooltip } from './TenoraTooltip';
export type { TenoraTooltipProps, TenoraTooltipTriggerProps, TenoraTooltipContentProps, TenoraTooltipArrowProps } from './types';
