// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Tooltip } from '@heroui/react';
import type { TenoraTooltipProps, TenoraTooltipTriggerProps, TenoraTooltipContentProps, TenoraTooltipArrowProps } from './types';

function TenoraTooltipRoot(props: TenoraTooltipProps) {
  return <Tooltip {...props} />;
}

function TenoraTooltipTrigger(props: TenoraTooltipTriggerProps) {
  return <Tooltip.Trigger {...props} />;
}

function TenoraTooltipContent(props: TenoraTooltipContentProps) {
  return <Tooltip.Content {...props} />;
}

function TenoraTooltipArrow(props: TenoraTooltipArrowProps) {
  return <Tooltip.Arrow {...props} />;
}

export const TenoraTooltip = Object.assign(TenoraTooltipRoot, {
  Root: TenoraTooltipRoot,
  Trigger: TenoraTooltipTrigger,
  Content: TenoraTooltipContent,
  Arrow: TenoraTooltipArrow,
});
