// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Tooltip } from '@heroui/react';

export type TenoraTooltipProps = ComponentProps<typeof Tooltip>;
export type TenoraTooltipTriggerProps = ComponentProps<typeof Tooltip.Trigger>;
export type TenoraTooltipContentProps = ComponentProps<typeof Tooltip.Content>;
export type TenoraTooltipArrowProps = ComponentProps<typeof Tooltip.Arrow>;
