// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { ColorSwatch } from '@heroui/react';
import type { TenoraColorSwatchProps } from './types';

function TenoraColorSwatchRoot(props: TenoraColorSwatchProps) {
  return <ColorSwatch {...props} />;
}



export const TenoraColorSwatch = Object.assign(TenoraColorSwatchRoot, {
  Root: TenoraColorSwatchRoot,
});
