// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Toast } from '@heroui/react';
import type { TenoraToastProps, TenoraToastProviderProps } from './types';

function TenoraToastRoot(props: TenoraToastProps) {
  return <Toast {...props} />;
}

function TenoraToastProvider(props: TenoraToastProviderProps) {
  return <Toast.Provider {...props} />;
}

export const TenoraToast = Object.assign(TenoraToastRoot, {
  Root: TenoraToastRoot,
  Provider: TenoraToastProvider,
});
