// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Toast } from '@heroui/react';

export type TenoraToastProps = ComponentProps<typeof Toast>;
export type TenoraToastProviderProps = ComponentProps<typeof Toast.Provider>;
