// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { TenoraPopover } from './TenoraPopover';
export type { TenoraPopoverProps, TenoraPopoverTriggerProps, TenoraPopoverDialogProps, TenoraPopoverArrowProps, TenoraPopoverContentProps, TenoraPopoverHeadingProps } from './types';
