// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import { Popover } from '@heroui/react';
import type { TenoraPopoverProps, TenoraPopoverTriggerProps, TenoraPopoverDialogProps, TenoraPopoverArrowProps, TenoraPopoverContentProps, TenoraPopoverHeadingProps } from './types';

function TenoraPopoverRoot(props: TenoraPopoverProps) {
  return <Popover {...props} />;
}

function TenoraPopoverTrigger(props: TenoraPopoverTriggerProps) {
  return <Popover.Trigger {...props} />;
}

function TenoraPopoverDialog(props: TenoraPopoverDialogProps) {
  return <Popover.Dialog {...props} />;
}

function TenoraPopoverArrow(props: TenoraPopoverArrowProps) {
  return <Popover.Arrow {...props} />;
}

function TenoraPopoverContent(props: TenoraPopoverContentProps) {
  return <Popover.Content {...props} />;
}

function TenoraPopoverHeading(props: TenoraPopoverHeadingProps) {
  return <Popover.Heading {...props} />;
}

export const TenoraPopover = Object.assign(TenoraPopoverRoot, {
  Root: TenoraPopoverRoot,
  Trigger: TenoraPopoverTrigger,
  Dialog: TenoraPopoverDialog,
  Arrow: TenoraPopoverArrow,
  Content: TenoraPopoverContent,
  Heading: TenoraPopoverHeading,
});
