// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Popover } from '@heroui/react';

export type TenoraPopoverProps = ComponentProps<typeof Popover>;
export type TenoraPopoverTriggerProps = ComponentProps<typeof Popover.Trigger>;
export type TenoraPopoverDialogProps = ComponentProps<typeof Popover.Dialog>;
export type TenoraPopoverArrowProps = ComponentProps<typeof Popover.Arrow>;
export type TenoraPopoverContentProps = ComponentProps<typeof Popover.Content>;
export type TenoraPopoverHeadingProps = ComponentProps<typeof Popover.Heading>;
