// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
import type { ComponentProps } from 'react';
import { Input } from '@heroui/react';

export type DunetaInputProps = ComponentProps<typeof Input>;

export type { DunetaDatePickerProps } from './DunetaDatePicker';
export type { DunetaInputEmailProps } from './DunetaInputEmail';
export type { DunetaInputNumberProps, DunetaInputNumberValue } from './DunetaInputNumber';
export type { DunetaInputPasswordProps } from './DunetaInputPassword';
export type { DunetaInputPhoneProps } from './DunetaInputPhone';
export type { DunetaInputSearchProps } from './DunetaInputSearch';
export type { DunetaTextAreaProps } from './DunetaTextArea';
