// AUTO-GENERATED by scripts/generate-ui-wrappers.mjs — do not edit.
export { DunetaBadge } from './DunetaBadge';
export type { DunetaBadgeProps, DunetaBadgeAnchorProps, DunetaBadgeLabelProps } from './types';
